// Roblox Analytics Query API catalog, checked 2026-09-30. Metric and dimension identifiers are case-sensitive.
// Source: https://github.com/Roblox/creator-docs/blob/main/content/en-us/cloud/guides/analytics/metrics.md
// Generated from the supported-metrics tables; no credentials or measured game data.

export const ANALYTICS_CATEGORIES = [
  "Retention",
  "Engagement",
  "Monetization",
  "Acquisition",
  "Performance & Stability",
  "Economy",
  "Funnels",
  "Custom Events",
  "Thumbnails",
  "Speech-to-Text",
  "Text-to-Speech",
  "Matchmaking",
  "Data Store",
  "Memory Stores",
  "Safety",
  "Advertising"
] as const;

const DIMENSIONS = [
  ["AcquisitionSource","AgeGroupV2","Country","Gender","Locale","OperatingSystem","Platform","UserO18Eligibility","UserSegmentationAccountAge","UserSegmentationActivationStatus","UserSegmentationEngagementLevel","UserSegmentationPayerStatus","UserSegmentationPlatformActivationStatus","UserSegmentationPlatformSpenderStatus"],
  ["AcquisitionSource","AgeGroupV2","CohortDay","Country","Gender","Locale","OperatingSystem","Platform","UserSegmentationAccountAge","UserSegmentationActivationStatus","UserSegmentationEngagementLevel","UserSegmentationPayerStatus","UserSegmentationPlatformActivationStatus","UserSegmentationPlatformSpenderStatus"],
  ["AcquisitionSource","AgeGroupV2","CohortWeek","Country","Gender","Locale","OperatingSystem","Platform","UserSegmentationAccountAge","UserSegmentationActivationStatus","UserSegmentationEngagementLevel","UserSegmentationPayerStatus","UserSegmentationPlatformActivationStatus","UserSegmentationPlatformSpenderStatus"],
  ["AgeGroupV2","Country","Gender","Locale","OperatingSystem","Platform","UserO18Eligibility","UserSegmentationAccountAge","UserSegmentationActivationStatus","UserSegmentationEngagementLevel","UserSegmentationPayerStatus","UserSegmentationPlatformActivationStatus","UserSegmentationPlatformSpenderStatus"],
  ["AgeGroupV2","Country","Gender","IsNewUser","Locale","OperatingSystem","Platform","UserO18Eligibility","UserSegmentationAccountAge","UserSegmentationActivationStatus","UserSegmentationEngagementLevel","UserSegmentationPayerStatus","UserSegmentationPlatformActivationStatus","UserSegmentationPlatformSpenderStatus"],
  ["AcquisitionSource","AgeGroupV2","Country","Gender","IsNewUser","Locale","OperatingSystem","Platform","UserO18Eligibility","UserSegmentationAccountAge","UserSegmentationActivationStatus","UserSegmentationEngagementLevel","UserSegmentationPayerStatus","UserSegmentationPlatformActivationStatus","UserSegmentationPlatformSpenderStatus"],
  ["AgeGroupV2","Gender","OperatingSystem","Platform","SessionTimeBucket","UserSegmentationAccountAge","UserSegmentationActivationStatus","UserSegmentationEngagementLevel","UserSegmentationPayerStatus","UserSegmentationPlatformActivationStatus","UserSegmentationPlatformSpenderStatus"],
  ["AgeGroupV2","BalanceType","Country","Gender","Locale","OperatingSystem","Platform","RevenueSource","UserO18Eligibility","UserSegmentationAccountAge","UserSegmentationActivationStatus","UserSegmentationEngagementLevel","UserSegmentationPayerStatus","UserSegmentationPlatformActivationStatus","UserSegmentationPlatformSpenderStatus"],
  ["CollectibleItemTargetType","CollectibleItemTargetTypeId","CollectibleItemType","ProductKey","ProductType","SalesLocation"],
  ["AcquisitionSource","AgeGroupV2","Gender","IsNewUser","OperatingSystem","Platform","UserSegmentationPlatformActivationStatus","UserSegmentationPlatformSpenderStatus"],
  ["AcquisitionSource","AgeGroupV2","FunnelSource","Gender","IsNewUser","OperatingSystem","Platform","UserSegmentationPlatformActivationStatus","UserSegmentationPlatformSpenderStatus"],
  ["AgeGroupV2","Gender"],
  ["ClientCpuTimeCategory","ClientCpuTimeSubCategory","MemoryGroup","OperatingSystem","Place","PlaceVersion","Platform"],
  ["MemoryGroup","OperatingSystem","Place","PlaceVersion","Platform"],
  ["Place"],
  ["SimplifiedUrl"],
  ["CpuTimeCategory","CpuTimeSubCategory","Place"],
  ["CrashType","Place"],
  ["MemoryUsageCategory","MemoryUsageSubCategory","Place","ServerAgeBucket"],
  ["AgeGroup","CurrencyType","CustomField1","CustomField2","CustomField3","Gender","IsNewUser","OperatingSystem","PayerStatus","Platform"],
  ["AgeGroup","CurrencyType","CustomField1","CustomField2","CustomField3","FlowType","Gender","IsNewUser","ItemSku","OperatingSystem","PayerStatus","Platform","TransactionType"],
  ["AgeGroup","CustomField1","CustomField2","CustomField3","FunnelName","FunnelStep","Gender","IsNewUser","OperatingSystem","PayerStatus","Platform"],
  ["AgeGroup","CustomEventName","CustomField1","CustomField2","CustomField3","Gender","IsNewUser","OperatingSystem","PayerStatus","Platform"],
  ["ThumbnailAsset","ThumbnailList"],
  ["SpeechToTextTranscriptionStatus"],
  [],
  ["TextToSpeechRawAudioStatus"],
  ["AgeGroup","Locale","MatchmakingCategoricalCustomSignal","Place","Platform"],
  ["AgeGroup","Locale","MatchmakingNumericCustomSignal","Place","Platform"],
  ["AgeGroup","Country","Locale","Place","Platform"],
  ["DataStoreRequestSource","DataStoreTypeV2"],
  ["DataStoreTypeV2"],
  ["DataStoreOperation","DataStoreTypeV2"],
  ["DataStoreOperation","DataStoreStatus","DataStoreTypeV2"],
  ["DataStoreStatus","DataStoreTypeV2"],
  ["MemoryStoreOperation"],
  ["MemoryStoreOperation","MemoryStoreStatus"],
  ["MemoryStoreStatus"],
  ["AbuseCategory","AbuseChannel"],
  ["AdFormat","AdInstanceName","AdPlacementId","AdsPublisherReportingDataVersion","Country","Gender","OperatingSystem","Platform"],
  ["AdFormat","AdInstanceName","AdPlacementId","AdsPublisherReportingDataVersion","Country","Gender","OperatingSystem","PlacementType","Platform"],
] as const;
const GRANULARITIES = [
  ["OneDay"],
  ["None","OneDay"],
  ["None","OneWeek"],
  ["OneDay","OneWeek","OneMonth","None"],
  ["OneHour","OneDay","None"],
  ["OneDay","None"],
  ["OneDay","None","OneWeek"],
  ["OneMinute","HalfHour","OneHour","OneDay"],
  ["OneDay","OneHour","None"],
  ["OneMinute","HalfHour","OneHour","OneDay","None"],
  ["OneDay","OneHour","OneWeek","OneMonth","None"],
  ["None"],
  ["OneHour","OneDay"],
] as const;

// category index, label, metric IDs, granularity set, retention days, dimension set.
export const CATALOG_ROWS: readonly (readonly [number, string, readonly string[], number, number, number])[] = [
  [0,"Day 1 retention",["ForwardD1Retention"],0,1468,0],
  [0,"Day 7 retention",["ForwardD7Retention"],0,1468,0],
  [0,"Day 30 retention",["ForwardD30Retention"],0,1468,0],
  [0,"Daily cohort retention",["DailyCohortRetention"],1,1468,1],
  [0,"Weekly cohort retention",["WeeklyCohortRetention"],2,1468,2],
  [0,"Stickiness (DAU/MAU)",["DauMauStickiness"],0,1468,3],
  [1,"Average playtime",["AveragePlayTimeMinutesPerDAU"],3,1468,4],
  [1,"Average session time",["AverageSessionLengthMinutes"],3,1468,4],
  [1,"Daily active users",["DailyActiveUsers"],3,1468,5],
  [1,"Monthly active users",["MonthlyActiveUsers"],0,1468,4],
  [1,"Playtime",["TotalPlayTimeHours"],3,1468,4],
  [1,"New user first session retention",["TotalSessionsEndedInBucket"],3,1468,6],
  [1,"Sessions",["Visits"],3,1468,4],
  [2,"Average revenue per paying user (ARPPU)",["AverageRevenuePerPayingUser"],3,1468,3],
  [2,"Average revenue per DAU (ARPDAU)",["AverageRevenuePerUser"],3,1468,3],
  [2,"Revenue",["DailyRevenue"],3,1468,7],
  [2,"Robux Spent (Realtime)",["ItemMonetizationRevenue"],4,1468,8],
  [2,"Paying users",["PayingUsers"],3,1468,3],
  [2,"Payer conversion rate",["PayingUsersCVR"],3,1468,3],
  [3,"Users detail page CTR",["ClickCVR"],5,1468,9],
  [3,"Play rate per unique user",["EndToEndCVR"],5,1468,9],
  [3,"Users impression CTR",["ImpressionCVR"],5,1468,9],
  [3,"Qualified play through rate per user",["QualifiedEndToEndCVR"],5,1468,9],
  [3,"Unique users with qualified plays",["QualifiedUniqueUsersWithPlaySessions"],6,1468,10],
  [3,"Deep play through rate",["RFYDeepEngagementRate"],0,1468,11],
  [3,"Play through rate",["RFYPlayThroughRate"],0,1468,11],
  [3,"Qualified play through rate (recommendations)",["RFYQualifiedPTR"],0,1468,11],
  [3,"Users with detail page visits",["UniqueUsersWithClicks"],5,1468,9],
  [3,"Unique users with impressions",["UniqueUsersWithImpressions"],5,1468,9],
  [3,"Unique users with plays",["UniqueUsersWithPlaySessions"],6,1468,10],
  [4,"Client CPU time",["ClientCpuTimeAvg"],7,28,12],
  [4,"Client crash count",["ClientCrashCount"],7,28,13],
  [4,"Client crash rate",["ClientCrashRate15m"],7,28,13],
  [4,"Client frame rate",["ClientFpsAvg","ClientFpsP10","ClientFpsP50","ClientFpsP90"],7,28,13],
  [4,"Client memory usage",["ClientMemoryUsageAvg","ClientMemoryUsageP10","ClientMemoryUsageP50","ClientMemoryUsageP90"],7,28,13],
  [4,"Client memory usage percentage",["ClientMemoryUsagePercentageAvg","ClientMemoryUsagePercentageP10","ClientMemoryUsagePercentageP50","ClientMemoryUsagePercentageP90"],7,28,13],
  [4,"CPU core utilization",["CpuCoreUtilization"],7,28,14],
  [4,"Unexpected out of memory exits",["OomUnexpectedExits"],7,28,13],
  [4,"Peak concurrent players",["PeakConcurrentPlayers"],7,28,13],
  [4,"Client API calls in first 60s after join",["RotraceTotalCalls"],8,365,15],
  [4,"Server CPU time",["CpuTimeAvg","CpuTimeP10","CpuTimeP50","CpuTimeP90"],7,28,16],
  [4,"Server crashes",["ServerCrashCount"],7,28,17],
  [4,"Server frame rate",["ServerFrameRateAvg","ServerFrameRateP10","ServerFrameRateP50","ServerFrameRateP90"],7,28,14],
  [4,"Server memory usage by age",["MemoryUsageAvg","MemoryUsageP10","MemoryUsageP50","MemoryUsageP90"],9,28,18],
  [4,"Server memory usage",["MemoryUsageAvg","MemoryUsageP10","MemoryUsageP50","MemoryUsageP90"],9,28,18],
  [4,"Session time",["SessionDurationSecondsAvg","SessionDurationSecondsP10","SessionDurationSecondsP50","SessionDurationSecondsP90"],7,28,13],
  [5,"Average wallet balance",["EconomyAverageWalletBalance"],10,1468,19],
  [5,"Transaction amount",["EconomyTransactionAmount"],10,1468,20],
  [5,"Transactions",["EconomyTransactionCount"],10,1468,20],
  [6,"Cohort completion rate",["FunnelCohortCompletionRate"],5,1468,21],
  [6,"Session cohort completion rate",["FunnelCohortSessionCompletionRate"],5,1468,21],
  [6,"Churn",["FunnelStepChurnRate"],11,1468,21],
  [6,"Step completion",["FunnelStepCompletionRate"],11,1468,21],
  [6,"Total conversion",["FunnelStepOverallCompletionRate"],11,1468,21],
  [6,"Total Sessions",["FunnelStepTotalCount"],11,1468,21],
  [6,"Churn",["FunnelUserChurnRate"],11,1468,21],
  [6,"Total conversion",["FunnelUserOverallCompletionRate"],11,1468,21],
  [6,"Step completion",["FunnelUserStepCompletionRate"],11,1468,21],
  [6,"Total users",["FunnelUserTotalCount"],11,1468,21],
  [7,"Custom events",["CustomEventAvgPerUserValue","CustomEventAvgValue","CustomEventCount","CustomEventCountUser","CustomEventMaxValue","CustomEventMinValue","CustomEventSumValue"],10,1468,22],
  [8,"Average session length by thumbnail",["ThumbnailAverageSessionLengthMinutes"],8,30,23],
  [8,"Impressions by thumbnail",["ThumbnailImpressions"],8,30,23],
  [8,"7D qualified play through rate by thumbnail (cumulative)",["ThumbnailL7QualifiedPTR"],8,30,23],
  [8,"Qualified play through rate by thumbnail",["ThumbnailQualifiedPTR"],8,30,23],
  [8,"Qualified plays by thumbnail",["ThumbnailQualifiedPlays"],8,30,23],
  [8,"Winning segments by thumbnail",["ThumbnailWinningSegments"],8,30,23],
  [9,"Audio transcription API responses by status",["SpeechToTextTranscriptionStatuses"],7,28,24],
  [9,"Audio transcription API usage",["SpeechToTextTranscriptionUsage"],7,28,24],
  [10,"Audio generation API asset generation successes",["TextToSpeechAssetSuccesses"],7,28,25],
  [10,"Audio generation API responses by status",["TextToSpeechRawAudioErrors"],7,28,26],
  [10,"Audio generation API usage",["TextToSpeechRawAudioSuccesses"],7,28,26],
  [11,"Categorical custom signal similarity ratio",["MatchmakingCategoricalCustomSignalsSimilarityRatioAvg","MatchmakingCategoricalCustomSignalsSimilarityRatioP10","MatchmakingCategoricalCustomSignalsSimilarityRatioP50","MatchmakingCategoricalCustomSignalsSimilarityRatioP90"],4,90,27],
  [11,"Numerical custom signal difference",["MatchmakingNumericCustomSignalsDifferenceAvg","MatchmakingNumericCustomSignalsDifferenceP10","MatchmakingNumericCustomSignalsDifferenceP50","MatchmakingNumericCustomSignalsDifferenceP90"],4,90,28],
  [11,"Age difference",["MatchmakingSignalsAgeDifferenceAvg","MatchmakingSignalsAgeDifferenceP10","MatchmakingSignalsAgeDifferenceP50","MatchmakingSignalsAgeDifferenceP90"],12,90,29],
  [11,"Common text chat ratio",["MatchmakingSignalsCommonChatGroupRatioAvg","MatchmakingSignalsCommonChatGroupRatioP10","MatchmakingSignalsCommonChatGroupRatioP50","MatchmakingSignalsCommonChatGroupRatioP90"],12,90,29],
  [11,"Common device ratio",["MatchmakingSignalsCommonDeviceTypeRatioAvg","MatchmakingSignalsCommonDeviceTypeRatioP10","MatchmakingSignalsCommonDeviceTypeRatioP50","MatchmakingSignalsCommonDeviceTypeRatioP90"],12,90,29],
  [11,"Common language ratio",["MatchmakingSignalsCommonLanguageRatioAvg","MatchmakingSignalsCommonLanguageRatioP10","MatchmakingSignalsCommonLanguageRatioP50","MatchmakingSignalsCommonLanguageRatioP90"],12,90,29],
  [11,"Estimated ping",["MatchmakingSignalsEstimatePingAvg","MatchmakingSignalsEstimatePingP10","MatchmakingSignalsEstimatePingP50","MatchmakingSignalsEstimatePingP90"],12,90,29],
  [11,"Occupancy ratio",["MatchmakingSignalsOccupancyRatioAvg","MatchmakingSignalsOccupancyRatioP10","MatchmakingSignalsOccupancyRatioP50","MatchmakingSignalsOccupancyRatioP90"],12,90,29],
  [11,"Play history difference",["MatchmakingSignalsPlayHistoryDifferenceAvg","MatchmakingSignalsPlayHistoryDifferenceP10","MatchmakingSignalsPlayHistoryDifferenceP50","MatchmakingSignalsPlayHistoryDifferenceP90"],12,90,29],
  [11,"Average friends match ratio",["MatchmakingSignalsPreferredPlayerMatchRatioAvg"],12,90,29],
  [11,"Voice chat ratio",["MatchmakingSignalsVoiceChatRatioAvg","MatchmakingSignalsVoiceChatRatioP10","MatchmakingSignalsVoiceChatRatioP50","MatchmakingSignalsVoiceChatRatioP90"],12,90,29],
  [12,"List request quota consumption",["DataStoreConsumedListRequests"],7,28,30],
  [12,"Read request quota consumption",["DataStoreConsumedReadRequests"],7,28,30],
  [12,"Remove request quota consumption",["DataStoreConsumedRemoveRequests"],7,28,30],
  [12,"Write request quota consumption",["DataStoreConsumedWriteRequests"],7,28,30],
  [12,"List quota usage",["DataStoreListRequests"],7,28,31],
  [12,"List quota usage",["DataStoreListRequestsByEndpoint"],7,28,32],
  [12,"Read quota usage",["DataStoreReadRequests"],7,28,31],
  [12,"Read quota usage",["DataStoreReadRequestsByEndpoint"],7,28,32],
  [12,"Remove quota usage",["DataStoreRemoveRequests"],7,28,31],
  [12,"Remove quota usage",["DataStoreRemoveRequestsByEndpoint"],7,28,32],
  [12,"Request count by API and status",["DataStoreRequests"],7,28,33],
  [12,"Request count by API",["DataStoreRequestsByEndpoint"],7,28,32],
  [12,"Request count by status",["DataStoreRequestsByStatus"],7,28,34],
  [12,"Storage usage",["DataStoreStorageUsageBytes"],7,28,25],
  [12,"Write quota usage",["DataStoreWriteRequests"],7,28,31],
  [12,"Write quota usage",["DataStoreWriteRequestsByEndpoint"],7,28,32],
  [13,"Memory usage",["MemoryStoreMemoryUsageBytes"],7,28,25],
  [13,"API request units",["MemoryStoreRequestUnitsByEndpoint"],7,28,35],
  [13,"Request count by API and status",["MemoryStoreRequests"],7,28,36],
  [13,"Request count by API",["MemoryStoreRequestsByEndpoint"],7,28,35],
  [13,"Request count by status",["MemoryStoreRequestsByStatus"],7,28,37],
  [14,"Total abuse reports",["TotalAbuseReports"],0,1468,38],
  [14,"Abuse report submitters per 1000 playtime hours",["UniqueAbuseReportSubmittersPer1000PlaytimeHours"],0,1468,38],
  [15,"Impressions",["AdsPublisherReportingTotalImpressions"],8,1468,39],
  [15,"Total revenue",["AdsPublisherReportingTotalRevenueRobux"],8,1468,39],
  [15,"Rewarded video daily unique viewers",["AdsPublisherReportingVideo2DDailyUniqueViewer"],5,1468,40],
  [15,"Rewarded video earnings per mille (EPM)",["AdsPublisherReportingVideo2DEpmNoUnvalidatedPc"],8,1468,40],
  [15,"Rewarded video impressions",["AdsPublisherReportingVideo2DImpressions"],8,1468,40],
  [15,"Rewarded video earnings",["AdsPublisherReportingVideo2DRevenueRobux"],8,1468,40],
];

export { DIMENSIONS, GRANULARITIES };
